stages:
  - build
  - publish

building_dockerfile:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t 2048-game .
  
  publish_to_dockerhub:
    stage: publish
    script:
      - docker push $DOCKER_USERNAME/2048-game