image: docker:19.03.13

variables:
    DOCKER_TLS_CERTDIR: "/certs"
services:
    -   name: docker:19.03.13-dind
        alias: docker
stages:
  - build-docker-image
  
build-docker-image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t 2048 .