services:
  - docker:dind
image: docker:stable

stages:
  - build
  - deploy

building_dockerfile:
  stage: build
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t 2048-game .
    
deploy_image:
  stage: deploy
  script:
    - docker push $DOCKER_USERNAME/2048-game