stages:
  - build
build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t mydockerimage .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE