services:
  - docker:dind
image: docker:stable

stages:
  - build
  - deploy

building_dockerfile:
  stage: build
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t my-simple-tasks:latest .
    
deploy_image:
  stage: deploy
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker push $DOCKER_USERNAME/my-simple-tasks:latest
