services:
  - docker:dind
image: docker:stable

stages:
  - build
  - deploy

building_dockerfile:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/zubkovsuper/my-simple-tasks .

    
deploy_image:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push registry.gitlab.com/zubkovsuper/my-simple-tasks
